version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
       - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    container_name: dbt
    image: dbt-dummy #dbtlabs/dbt:latest
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/dbts
    ports:
      - "8080:8080"
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
      DBT_TARGET: dev
    depends_on:
      - postgres