
version: 2

models:
  - name: champion_stores
    description: Top 10 stores per transacted amount.
    columns:
      - name: store_id
        description: Unique id of store.
      - name: store_name
        description: Name of store.
      - name: total_amount
        description: Total amount of the store transacted.
      - name: rank
        description: Rank of the store based on total_amount

  - name: champion_products
    description: Top 10 products sold.
    columns:
      - name: product_name
        description: Name of the product.
      - name: total_amount
        description: Total amount of the product sold.
      - name: rank
        description: Rank of the product based on total_amount

  - name: kpi_avg_amount_store
    description: Average transacted amount per store typology and country.
    columns:
      - name: store_typology
        description: Typology of the store.
      - name: store_country
        description: Country of the store.
      - name: average_amount
        description: Average amount value.

  - name: kpi_amount_device
    description: Percentage of transactions per device type.
    columns:
      - name: device_type
        description: Type of the device.
      - name: amount_per_device
        description: Amount value per device_type.
      - name: total_amount
        description: Total amount value.
      - name: percentage
        description: Percentage value.


  - name: kpi_avg_time_transaction_store
    description: Average time for a store to perform its 5 first transactions.
    columns:
      - name: store_name
        description: Name of store.
      - name: average_time
        description: Average time duration in seconds of its first 5 transactions.