dbt-project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: postgres
      port: 5432
      dbname: postgres
      schema: postgres
      threads: 4